//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Web_Ingenieria_de_Software.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaImagen
    {
        public int ID { get; set; }
        public int SalonID { get; set; }
        public System.DateTime Time { get; set; }
        public int FacturaNumero { get; set; }
        public int EmployeeID { get; set; }
        public string ClientName { get; set; }
        public byte[] FacturaImage { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
