//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Web_Ingenieria_de_Software.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public int FacturaNumero { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public int ID { get; set; }
        public string itemSale { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
