//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Web_Ingenieria_de_Software.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int ID { get; set; }
        public string Day { get; set; }
        public bool Weekday { get; set; }
        public int OpenTime { get; set; }
        public int CloseTime { get; set; }
    
        public virtual Horas Horas { get; set; }
        public virtual Horas Horas1 { get; set; }
    }
}
