//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Web_Ingenieria_de_Software.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public int ID { get; set; }
        public int ModuleID { get; set; }
        public int UserID { get; set; }
    
        public virtual Modules Modules { get; set; }
        public virtual Users Users { get; set; }
    }
}
