//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Web_Ingenieria_de_Software.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDetail
    {
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public int ProductID { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Services Services { get; set; }
    }
}
